apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 408223505404.dkr.ecr.ap-northeast-2.amazonaws.com/khb-test:latest
        volumeMounts:
        - name: persistent-storage
          mountPath: /static
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
      imagePullSecrets:
      - name: ecr-credentials
