apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  clusterIP: 172.30.10.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: 408223505404.dkr.ecr.ap-northeast-2.amazonaws.com/tomcat:1.2
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 150m
            memory: 200Mi
      imagePullSecrets:
      - name: ecr-credentials
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tomcat-hpa
spec:
  maxReplicas: 20
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tomcat
  targetCPUUtilizationPercentage: 50
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tomcat-cronjob
spec:
  schedule: "0 0 */8 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tomcat
            image: 408223505404.dkr.ecr.ap-northeast-2.amazonaws.com/tomcat:1.1
            resources:
              limits:
                cpu: 500m
                memory: 1024Mi
              requests:
                cpu: 300m
                memory: 500Mi
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: ecr-credentials
