
---
- hosts: localhost
  vars_files: ./vars.yaml

  tasks: 
    - name: Create a Project VMs
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'
        datacenter: '{{datacenter_name}}'
        folder: '{{ folder_prefix }}'

        name: '{{ project_id + item.vmname }}'
        state: poweredoff
        guest_id: '{{ item.guest_id }}'
        esxi_hostname: "{{ esxi_hostname }}"
        hardware:
          num_cpus: '{{ item.cpus }}'
          memory_mb: '{{ item.memory }}'
          scsi: paravirtual
        disk:
        - size_gb: '{{ item.disk_gb }}'
          type: thin
          datastore: '{{ datastore_name }}'
        networks:
        - name: '{{ private_net }}'
          device_type: vmxnet3
        cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: '{{ iso_folder + item.iso }}'
      loop:
      - { vmname: -Bastion, guest_id: rhel8_64Guest, cpus: 4, memory: 16384, disk_gb: 120, iso: CentOS-7-x86_64-DVD-2009.iso }
      - { vmname: -TrueNAS, guest_id: freebsd64Guest, cpus: 4, memory: 16384,  disk_gb: 32, iso: TrueNAS-13.0-U4.iso }
      - { vmname: -Untangle, guest_id: debian9_64Guest, cpus: 4, memory: 8192,  disk_gb: 32, iso: ngfw-untangle-15.1.1-amd64.iso }
      delegate_to: localhost
      register: deploy_vm
