apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /mnt/NFS/NFS
    server: 10.0.0.2 
  persistentVolumeReclaimPolicy: Retain
